# Generated by Django 3.2.16 on 2022-11-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('done_date', models.DateTimeField(verbose_name='Дата выполнения')),
                ('done', models.BooleanField()),
            ],
        ),
    ]
